site_name: EXtra
site_url: https://extra.readthedocs.io
repo_url: https://github.com/european-xfel/extra

theme:
  name: material
  logo: images/logo.jpg
  favicon: images/logo.jpg
  font:
    text: Open Sans
  features:
    - content.code.annotate
    - navigation.instant

nav:
  - index.md
  - reading-data.md
  - detector-geometry.md
  - components.md
  - karabo-bridge.md
  - utilities.md
  - changelog.md

watch:
  - src

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.saneheaders
  - pymdownx.emoji
  - pymdownx.magiclink:
      repo_url_shorthand: true
      normalize_issue_symbols: true
      user: European-XFEL
      repo: EXtra
  - tables
  - attr_list
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://extra-data.readthedocs.io/en/latest/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
          options:
            docstring_style: google
            separate_signature: yes
            show_signature_annotations: yes
            merge_init_into_class: yes
            show_submodules: yes
            members_order: source
            show_root_heading: yes
            heading_level: 3
            show_source: no
            inherited_members: yes

extra_css:
  - css/mkdocstrings.css

extra_javascript:
  - css/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
